import type { StampTemplate } from '../types/stamp';

export const DEFAULT_TEMPLATES: StampTemplate[] = [
  {
    id: 'notary-classic',
    name: 'Notaría & Registro Legal',
    category: 'notary',
    description: 'Sello formal notarial con doble borde, texto en arco superior e inferior y escudo central.',
    project: {
      title: 'Sello Notarial',
      shape: 'circle',
      widthMm: 42,
      heightMm: 42,
      color: '#1e3a8a',
      grungeEffect: 0,
      showGrid: true,
      layers: [
        {
          id: 'frame-outer',
          type: 'frame',
          name: 'Marco Exterior Doble',
          visible: true,
          radius: 94,
          strokeWidth: 3,
          style: 'double',
          doubleGap: 4,
        },
        {
          id: 'text-top',
          type: 'circular-text',
          name: 'Texto Superior',
          visible: true,
          text: 'NOTARÍA PÚBLICA DE LA CIUDAD',
          radius: 82,
          startAngle: 0,
          sweepAngle: 180,
          letterSpacing: 2,
          fontFamily: 'Cinzel',
          fontSize: 16,
          isBold: true,
          isItalic: false,
          isReversed: false,
          position: 'top',
        },
        {
          id: 'text-bottom',
          type: 'circular-text',
          name: 'Texto Inferior',
          visible: true,
          text: 'REPÚBLICA • REGISTRO OFICIAL',
          radius: 82,
          startAngle: 180,
          sweepAngle: 180,
          letterSpacing: 2.5,
          fontFamily: 'Cinzel',
          fontSize: 14,
          isBold: true,
          isItalic: false,
          isReversed: true,
          position: 'bottom',
        },
        {
          id: 'frame-inner',
          type: 'frame',
          name: 'Borde Interior Fino',
          visible: true,
          radius: 68,
          strokeWidth: 1.5,
          style: 'solid',
        },
        {
          id: 'icon-center',
          type: 'icon',
          name: 'Balanza de la Justicia',
          visible: true,
          iconKey: 'scale',
          size: 46,
          offsetX: 0,
          offsetY: -10,
          rotation: 0,
        },
        {
          id: 'text-center',
          type: 'center-text',
          name: 'Texto Central Lic.',
          visible: true,
          text: 'LIC. ALEJANDRO VALLE\nFOLIO Nº 84920',
          fontFamily: 'Montserrat',
          fontSize: 12,
          isBold: true,
          isItalic: false,
          alignment: 'center',
          offsetX: 0,
          offsetY: 34,
          letterSpacing: 1,
          lineHeight: 1.2,
        },
      ],
    },
  },
  {
    id: 'rect-signature-38x14',
    name: 'Sello de Firma & Cargo (38x14 mm)',
    category: 'rectangular',
    description: 'Sello estándar de oficina 38x14 mm ideal para nombres, títulos profesionales y firmas.',
    project: {
      title: 'Sello de Firma 38x14',
      shape: 'rectangle',
      widthMm: 38,
      heightMm: 14,
      color: '#1e3a8a',
      grungeEffect: 0,
      showGrid: true,
      layers: [
        {
          id: 'frame-rect-1',
          type: 'frame',
          name: 'Borde Rectangular Fino',
          visible: true,
          radius: 90,
          widthPercent: 94,
          heightPercent: 90,
          cornerRadius: 4,
          strokeWidth: 1.5,
          style: 'solid',
        },
        {
          id: 'text-name',
          type: 'center-text',
          name: 'Nombre del Profesional',
          visible: true,
          text: 'ING. CARLOS H. DELGADO',
          fontFamily: 'Montserrat',
          fontSize: 14,
          isBold: true,
          isItalic: false,
          alignment: 'center',
          offsetX: 0,
          offsetY: -12,
          letterSpacing: 0.5,
          lineHeight: 1.1,
        },
        {
          id: 'text-title',
          type: 'center-text',
          name: 'Cargo / Departamento',
          visible: true,
          text: 'GERENTE DE OPERACIONES\nCIP Nº 198421',
          fontFamily: 'Inter',
          fontSize: 10,
          isBold: false,
          isItalic: false,
          alignment: 'center',
          offsetX: 0,
          offsetY: 10,
          letterSpacing: 0.5,
          lineHeight: 1.2,
        },
      ],
    },
  },
  {
    id: 'rect-company-47x18',
    name: 'Sello Comercial Empresa (47x18 mm)',
    category: 'rectangular',
    description: 'Medida clásica de 47x18 mm con razón social, RUC / CUIT y datos de contacto.',
    project: {
      title: 'Sello Comercial 47x18',
      shape: 'rectangle',
      widthMm: 47,
      heightMm: 18,
      color: '#0f172a',
      grungeEffect: 0,
      showGrid: true,
      layers: [
        {
          id: 'frame-rect-2',
          type: 'frame',
          name: 'Borde Rectangular Doble',
          visible: true,
          radius: 90,
          widthPercent: 95,
          heightPercent: 92,
          cornerRadius: 3,
          strokeWidth: 1.5,
          style: 'double',
          doubleGap: 3,
        },
        {
          id: 'text-comp-name',
          type: 'center-text',
          name: 'Razón Social',
          visible: true,
          text: 'INVERSIONES & SERVICIOS GLOBALES S.A.',
          fontFamily: 'Oswald',
          fontSize: 14,
          isBold: true,
          isItalic: false,
          alignment: 'center',
          offsetX: 0,
          offsetY: -18,
          letterSpacing: 1,
          lineHeight: 1.1,
        },
        {
          id: 'text-comp-details',
          type: 'center-text',
          name: 'RUC y Dirección',
          visible: true,
          text: 'RUC / ID: 20549102931\nAV. LIBERTADORES 840 - OF. 402\nTEL: +54 (11) 4892-1100',
          fontFamily: 'Roboto',
          fontSize: 8.5,
          isBold: false,
          isItalic: false,
          alignment: 'center',
          offsetX: 0,
          offsetY: 6,
          letterSpacing: 0.2,
          lineHeight: 1.25,
        },
      ],
    },
  },
  {
    id: 'medical-doctor',
    name: 'Sello Médico Profesional (38 mm)',
    category: 'medical',
    description: 'Sello para recetas y consultas médicas con cruz sanitaria y matrícula profesional.',
    project: {
      title: 'Sello Médico Dr.',
      shape: 'circle',
      widthMm: 38,
      heightMm: 38,
      color: '#15803d',
      grungeEffect: 0,
      showGrid: true,
      layers: [
        {
          id: 'frame-1',
          type: 'frame',
          name: 'Borde Exterior Grueso',
          visible: true,
          radius: 94,
          strokeWidth: 3.5,
          style: 'solid',
        },
        {
          id: 'frame-2',
          type: 'frame',
          name: 'Borde Interior Punteado',
          visible: true,
          radius: 88,
          strokeWidth: 1.5,
          style: 'dashed',
        },
        {
          id: 'text-top-med',
          type: 'circular-text',
          name: 'Especialidad',
          visible: true,
          text: 'MEDICINA GENERAL & CIRUGÍA',
          radius: 76,
          startAngle: 0,
          sweepAngle: 180,
          letterSpacing: 2,
          fontFamily: 'Montserrat',
          fontSize: 15,
          isBold: true,
          isItalic: false,
          isReversed: false,
          position: 'top',
        },
        {
          id: 'text-bot-med',
          type: 'circular-text',
          name: 'Institución / Ciudad',
          visible: true,
          text: 'HOSPITAL CENTRAL DE SALUD',
          radius: 76,
          startAngle: 180,
          sweepAngle: 180,
          letterSpacing: 2,
          fontFamily: 'Montserrat',
          fontSize: 13,
          isBold: true,
          isItalic: false,
          isReversed: true,
          position: 'bottom',
        },
        {
          id: 'icon-cross',
          type: 'icon',
          name: 'Cruz Médica',
          visible: true,
          iconKey: 'cross',
          size: 36,
          offsetX: 0,
          offsetY: -16,
          rotation: 0,
        },
        {
          id: 'text-name-med',
          type: 'center-text',
          name: 'Nombre y Matrícula',
          visible: true,
          text: 'DRA. SOFÍA MENDOZA\nM.P. 14.892 - M.N. 59.201',
          fontFamily: 'Inter',
          fontSize: 13,
          isBold: true,
          isItalic: false,
          alignment: 'center',
          offsetX: 0,
          offsetY: 28,
          letterSpacing: 0.5,
          lineHeight: 1.3,
        },
      ],
    },
  },
  {
    id: 'business-paid',
    name: 'Empresa / PAGADO / APROBADO (40 mm)',
    category: 'business',
    description: 'Sello comercial para facturas, contabilidad y recepción de documentos.',
    project: {
      title: 'Sello Pagado',
      shape: 'circle',
      widthMm: 40,
      heightMm: 40,
      color: '#b91c1c',
      grungeEffect: 15,
      showGrid: true,
      layers: [
        {
          id: 'frame-paid',
          type: 'frame',
          name: 'Marco Festoneado',
          visible: true,
          radius: 92,
          strokeWidth: 2.5,
          style: 'scalloped',
          scallopCount: 40,
        },
        {
          id: 'frame-paid-inner',
          type: 'frame',
          name: 'Borde Interior',
          visible: true,
          radius: 82,
          strokeWidth: 2,
          style: 'solid',
        },
        {
          id: 'text-top-corp',
          type: 'circular-text',
          name: 'Razón Social',
          visible: true,
          text: 'CORPORACIÓN LOGÍSTICA S.A.',
          radius: 70,
          startAngle: 0,
          sweepAngle: 180,
          letterSpacing: 2,
          fontFamily: 'Oswald',
          fontSize: 17,
          isBold: true,
          isItalic: false,
          isReversed: false,
          position: 'top',
        },
        {
          id: 'text-center-status',
          type: 'center-text',
          name: 'Estado PAGADO',
          visible: true,
          text: '★ PAGADO ★',
          fontFamily: 'Oswald',
          fontSize: 26,
          isBold: true,
          isItalic: false,
          alignment: 'center',
          offsetX: 0,
          offsetY: 0,
          letterSpacing: 3,
          lineHeight: 1,
        },
        {
          id: 'text-bot-corp',
          type: 'circular-text',
          name: 'Fecha y Control',
          visible: true,
          text: 'DPTO. DE CONTABILIDAD & FINANZAS',
          radius: 70,
          startAngle: 180,
          sweepAngle: 180,
          letterSpacing: 1.5,
          fontFamily: 'Montserrat',
          fontSize: 11,
          isBold: true,
          isItalic: false,
          isReversed: true,
          position: 'bottom',
        },
      ],
    },
  },
];
